import { useState } from 'react';
import Button from 'react-bootstrap/Button';
import Modal from 'react-bootstrap/Modal';
import './popup.css'

function Popup_Ford() {
    const [show, setShow] = useState(false);

    const handleClose = () => setShow(false);
    const handleShow = () => setShow(true);

    return (
        <>
            <Button variant="secondary" onClick={handleShow}>
                See More
            </Button>

            <Modal show={show} onHide={handleClose}>
                <Modal.Header closeButton>
                    <Modal.Title>Ford</Modal.Title>
                </Modal.Header>
                <Modal.Body><h3>Detail</h3>
                    <p>Ford Motor Company (commonly known as Ford) is an American multinational automobile manufacturer headquartered in Dearborn, Michigan, United States. It was founded by Henry Ford and incorporated on June 16, 1903. The company sells automobiles and commercial vehicles under the Ford brand, and luxury cars under its Lincoln brand. Ford also owns a 32% stake in China's Jiangling Motors. It also has joint ventures in China (Changan Ford), Taiwan (Ford Lio Ho), Thailand (AutoAlliance Thailand), and Turkey (Ford Otosan). The company is listed on the New York Stock Exchange and is controlled by the Ford family; they have minority ownership but the majority of the voting power.

                        Ford introduced methods for large-scale manufacturing of cars and large-scale management of an industrial workforce using elaborately engineered manufacturing sequences typified by moving assembly lines; by 1914, these methods were known around the world as Fordism. Ford's former UK subsidiaries Jaguar and Land Rover, acquired in 1989 and 2000, respectively, were sold to the Indian automaker Tata Motors in March 2008. Ford owned the Swedish automaker Volvo from 1999 to 2010. In 2011, Ford discontinued the Mercury brand, under which it had marketed entry-level luxury cars in the United States, Canada, Mexico, and the Middle East since 1938.

                        Ford is the second-largest U.S.-based automaker (behind General Motors) and the sixth-largest in the world (behind Toyota, Volkswagen Group, Hyundai Motor Group, Stellantis, and General Motors) based on 2022 vehicle production. At the end of 2010, Ford was the fifth-largest automaker in Europe. The company went public in 1956 but the Ford family, through special Class B shares, still retain 40 percent of the voting rights. During the financial crisis of 2007–08, the company struggled financially but did not have to be rescued by the federal government, unlike the other two major US automakers. Ford Motors has since returned to profitability, and was the eleventh-ranked overall American-based company in the 2018 Fortune 500 list, based on global revenues in 2017 of $156.7 billion. In 2008, Ford produced 5.532 million automobilesand employed about 213,000 employees at around 90 plants and facilities worldwide.</p>

                    <h3>History</h3>
                    <b>20th century</b>
                    <p>The Henry Ford Company was Henry Ford's first attempt at a car manufacturing company and was established on November 3, 1901. This became the Cadillac Motor Company on August 22, 1902, after Ford left with the rights to his name.The Ford Motor Company was launched in a converted factory in 1903 with $28,000 (equivalent to $912,000 in 2022) in cash from twelve investors, most notably John and Horace Dodge (who would later found their own car company). The first president was not Ford, but local banker John S. Gray, who was chosen in order to assuage investors' fears that Ford would leave the new company the way he had left its predecessor. During its early years, the company produced just a few cars a day at its factory on Mack Avenue and later at its factory on Piquette Avenue in Detroit, Michigan. Groups of two or three men worked on each car, assembling it from parts made mostly by supplier companies contracting for Ford. Within a decade the company led the world in the expansion and refinement of the assembly line concept, and Ford soon brought much of the part production in-house (vertical integration).

                        Henry Ford was 39 years old when he founded the Ford Motor Company, which would go on to become one of the world's largest and most profitable companies. It has been in continuous family control for over 100 years and is one of the largest family-controlled companies in the world.[citation needed]

                        The first gasoline-powered automobile had been created in 1885 by the German inventor Karl Benz (Benz Patent-Motorwagen). More efficient production methods were needed to make automobiles affordable for the middle class, to which Ford contributed by, for instance, introducing the first moving assembly line in 1913 at the Ford factory in Highland Park</p>

                    <p>Between 1903 and 1908, Ford produced the Models A, B, C, F, K, N, R, and S. Hundreds or a few thousand of most of these were sold per year. In 1908, Ford introduced the mass-produced Model T, which totaled millions sold over nearly 20 years. In 1927, Ford replaced the T with the Model A, the first car with safety glass in the windshield.Ford launched the first low-priced car with a V8 engine in 1932.[citation needed]

                        In an attempt to compete with General Motors' mid-priced Pontiac, Oldsmobile, and Buick, Ford created the Mercury in 1939 as a higher-priced companion car to Ford. Henry Ford purchased the Lincoln Motor Company in 1922, in order to compete with such brands as Cadillac and Packard for the luxury segment of the automobile market.[citation needed]

                        In 1929, Ford was contracted by the government of the Soviet Union to set up the Gorky Automobile Plant in Russia initially producing Ford Model A and AAs thereby playing an important role in the industrialization of that country</p>

                    <p>During World War II, the United States Department of War picked Ford to mass-produce the Consolidated B-24 Liberator bomber at its Willow Run assembly plant. Ford Werke and Ford SAF (Ford's subsidiaries in Germany and France, respectively) produced military vehicles and other equipment for Nazi Germany's war effort. Some of Ford's operations in Germany at the time were run using forced labor.

                        The creation of a scientific laboratory in Dearborn, Michigan, in 1951, doing unfettered basic research, led to Ford's unlikely involvement in superconductivity research. In 1964, Ford Research Labs made a key breakthrough with the invention of a superconducting quantum interference device or SQUID.
                        Ford offered the Lifeguard safety package from 1956, which included such innovations as a standard deep-dish steering wheel, optional front, and, for the first time in a car, rear seatbelts, and an optional padded dash.Ford introduced child-proof door locks into its products in 1957, and, in the same year, offered the first retractable hardtop on a mass-produced six-seater car.

                        In late 1955, Ford established the Continental division as a separate luxury car division. This division was responsible for the manufacture and sale of the famous Continental Mark II. At the same time, the Edsel division was created to design and market that car starting with the 1958 model year. Due to limited sales of the Continental and the Edsel disaster, Ford merged Mercury, Edsel, and Lincoln into "M-E-L," which reverted to "Lincoln-Mercury" after Edsel's November 1959 demise.

                        The Ford Mustang was introduced on April 17, 1964, during New York World's Fair (where Ford had a pavilion made by The Walt Disney Company). In 1965, Ford introduced the seat belt reminder light.[citation needed]

                        With the 1980s, Ford introduced several highly successful vehicles around the world. During the 1980s, Ford began using the advertising slogan, "Have you driven a Ford, lately?" to introduce new customers to their brand and make their vehicles appear more modern. In 1990 and 1994, respectively, Ford also acquired Jaguar Cars and Aston Martin. During the mid-to-late 1990s, Ford continued to sell large numbers of vehicles, in a booming American economy with a soaring stock market and low fuel prices.[citation needed]

                        With the dawn of the new century, legacy health care costs, higher fuel prices, and a faltering economy led to falling market shares, declining sales, and diminished profit margins. Most of the corporate profits came from financing consumer automobile loans through Ford Motor Credit Company.</p>

                    <b>21st century</b>

                    <p>By 2005, both Ford and GM's corporate bonds had been downgraded to junk status as a result of high U.S. health care costs for an aging workforce, soaring gasoline prices, eroding market share, and an overdependence on declining SUV sales. Profit margins decreased on large vehicles due to increased "incentives" (in the form of rebates or low-interest financing) to offset declining demand. In the latter half of 2005, Chairman Bill Ford asked newly appointed Ford Americas Division President Mark Fields to develop a plan to return the company to profitability. Fields previewed the plan, named The Way Forward, at the board meeting of the company on December 7, 2005, and it was unveiled to the public on January 23, 2006. "The Way Forward" included resizing the company to match market realities, dropping some unprofitable and inefficient models, consolidating production lines, closing 14 factories and cutting 30,000 jobs.

                        Ford moved to introduce a range of new vehicles, including "Crossover SUVs" built on unibody car platforms, rather than more body-on-frame chassis. In developing the hybrid electric powertrain technologies for the Ford Escape Hybrid SUV, the company licensed similar Toyota hybrid technologies in order to avoid patent infringements. Ford announced that it would team up with electricity supply company Southern California Edison (SCE) to examine the future of plug-in hybrids in terms of how home and vehicle energy systems will work with the electrical grid. Under the multimillion-dollar, multi-year project, Ford is to convert a demonstration fleet of Ford Escape Hybrids into plug-in hybrids, and SCE is to evaluate how the vehicles might interact with the home and the utility's electrical grid. Some of the vehicles are to be evaluated "in typical customer settings", according to Ford.

                        William Clay Ford Jr., great-grandson of Henry Ford (and better known by his nickname "Bill"), was appointed executive chairman in 1998, and also became chief executive officer of the company in 2001, with the departure of Jacques Nasser, becoming the first member of the Ford family to head the company since the retirement of his uncle, Henry Ford II, in 1982. Ford sold motorsport engineering company Cosworth to Gerald Forsythe and Kevin Kalkhoven in 2004, the start of a decrease in Ford's motorsport involvement. Upon the retirement of president and chief operations officer Jim Padilla in April 2006, Bill Ford assumed his roles as well. Five months later, in September, Ford named Alan Mulally as president and CEO, with Ford continuing as executive chairman. In December 2006, the company raised its borrowing capacity to about $25 billion, placing substantially all corporate assets as collateral. Chairman Bill Ford has stated that "bankruptcy is not an option".Ford and the United Auto Workers, representing approximately 46,000 hourly workers in North America, agreed to a historic contract settlement in November 2007 giving the company a substantial break in terms of its ongoing retiree health care costs and other economic issues. The agreement included the establishment of a company-funded, independently run Voluntary Employee Beneficiary Association (VEBA) trust to shift the burden of retiree health care from the company's books, thereby improving its balance sheet. This arrangement took effect on January 1, 2010. As a sign of its currently strong cash position, Ford contributed its entire current liability (estimated at US$5.5 billion as of December 31, 2009) to the VEBA in cash, and also pre-paid US$500 million of its future liabilities to the fund. The agreement also gave hourly workers the job security they were seeking by having the company commit to substantial investments in most of its factories</p>

                    <p>The automaker reported the largest annual loss in company history in 2006 of $12.7 billion, and estimated that it would not return to profitability until 2009. However, Ford surprised Wall Street in the second quarter of 2007 by posting a $750 million profit. Despite the gains, the company finished the year with a $2.7 billion loss, largely attributed to finance restructuring at Volvo.

                        On June 2, 2008, Ford sold its Jaguar and Land Rover operations to Tata Motors for $2.3 billion.

                        During congressional hearings held in November 2008 at Washington D.C., Ford's Alan Mulally stated that "We at Ford are hopeful that we have enough liquidity. But we also must prepare ourselves for the prospect of further deteriorating economic conditions". He went on to state that "The collapse of one of our competitors would have a severe impact on Ford" and that Ford Motor Company supported both Chrysler and General Motors in their search for government bridge loans in the face of conditions caused by the 2008 financial crisis. Together, the three companies presented action plans for the sustainability of the industry. Mulally stated that "In addition to our plan, we are also here today to request support for the industry. In the near-term, Ford does not require access to a government bridge loan. However, we request a credit line of $9 billion as a critical backstop or safeguard against worsening conditions as we drive transformational change in our company".GM and Chrysler received government loans and financing through T.A.R.P. legislation funding provisions.

                        On December 19, the cost of credit default swaps to insure the debt of Ford was 68 percent of the sum insured for five years, in addition to annual payments of 5 percent. That meant $6.8 million paid upfront to insure $10 million in debt, in addition to payments of $500,000 per year. In January 2009, Ford reported a $14.6 billion loss in the preceding year, a record for the company. The company retained sufficient liquidity to fund its operations. Through April 2009, Ford's strategy of debt-for-equity exchanges erased $9.9 billion in liabilities (28% of its total) in order to leverage its cash position.These actions yielded Ford a $2.7 billion profit in fiscal year 2009, the company's first full-year profit in four years.In 2012, Ford's corporate bonds were upgraded from junk to investment grade again, citing sustainable, lasting improvements.[51]

                        On October 29, 2012, Ford announced the sale of its climate control components business, its last remaining automotive components operation, to Detroit Thermal Systems LLC for an undisclosed price.

                        On November 1, 2012, Ford announced that CEO Alan Mulally would stay with the company until 2014. Ford also named Mark Fields, its president of operations in the Americas, as its new chief operating officer Mulally was paid a compensation of over $174 million in his previous seven years at Ford since 2006. The generous amount has been a sore point for some workers of the company.

                        In April 2016, Ford announced a plan to modernize its Dearborn engineering and headquarters campuses through a ten-year building project. The result would see the number of Ford employees working in these areas doubling, to 24,000. During construction, some 2000 of the employees were relocated out of the campus to a temporary location in a disused section of the local shopping mall. Facilities would also be altered to allow ride-sharing and electric and self-driving vehicles. Estimates of the construction cost were $1.2 billion</p>

                    <p>On January 3, 2017, Ford CEO Mark Fields announced that in a "vote of confidence" because of the pro-business climate being fostered in part by President-elect Donald Trump, Ford had canceled plans to invest $1.6 billion in a new plant in Mexico to manufacture the Ford Focus; instead, the company would invest $700 million in Michigan, which it planned to use to create 700 new jobs. The Focus would now be manufactured in the existing plant in Mexico.Also in 2017, Ford began development of a new mixed-use urban campus in the Corktown neighborhood of Detroit, with its purchase, renovation, and occupation of The Factory at Michigan and Rosa Parks. The new site was expected to have a major focus on the development of autonomous vehicle and electric vehicle technology.Ford later began buying up other parcels of land in Corktown including a very high-profile purchase of Michigan Central Station which is planned to become the hub of their Corktown campus, and the adjacent Roosevelt Warehouse.Ford expects to move 2,500 of its employees, roughly 5 percent of its southeast Michigan workforce, to the campus with space for an additional 2,500 entrepreneurs, technology companies and partners.Bill Ford envisioned the first-floor concourse of the train station to be a public gathering place with retail outlets and restaurants.

                        In February 2017, Ford Motor Co. acquired majority ownership of Argo AI, a self-driving car startup.

                        In May 2017, Ford announced cuts to its global workforce amid efforts to address the company's declining share price and to improve profits. The company is targeting $3 billion in cost reduction and a nearly 10% reduction in the salaried workforce in Asia and North America to enhance earnings in 2018.Jim Hackett was announced to replace Mark Fields as CEO of Ford Motor. Mr. Hackett most recently oversaw the formation of Ford Smart Mobility, a unit responsible for experimenting with car-sharing programs, self-driving ventures and other programs aimed at helping Ford better compete with Uber, Alphabet Inc. and other tech giants looking to edge in on the auto industry.

                        On April 25, 2018, Ford announced that it would discontinue passenger cars in the North American market in the next four years, except for the Mustang, due to declining demand and profitability. The Focus Active, a crossover SUV based on the newly unveiled fourth-generation Focus, was also intended to be marketed in the United States. Due to the vehicle being manufactured in China, Ford later announced that it would not release the Focus Active in the United States, due to tariffs imposed by the Trump administration on Chinese exports.

                        In March 2020, the Detroit United Auto Workers union announced that after discussion with the leaders of General Motors, Ford, and Fiat Chrysler Automobiles, the carmakers would partially shut down factories on a "rotating" basis to mitigate the COVID-19 pandemic.On March 24, representatives of Ford announced that production in the US, Canada, and Mexico would not resume on March 30 as originally planned, amid the further coronavirus pandemic spread. In the first quarter of 2020, Ford's sales dropped by 15%, entailing the loss of $2 billion.

                        With the change in the demand for the sport vehicles, on January 6, 2021, Ford reported a sales fall of 9.8% in the fourth quarter, selling 542,749 vehicles, compared to 601,862 in 2019.

                        In April 2021, Ford said that it would provide COVID-19 vaccines for its employees, who were to obtain them at the company; at the beginning the vaccination program would be in southeast Michigan, Missouri and Ohio, but it was to be expanded later on to other locations.

                        In March 2022, Ford announced that it would restructure the company into three separate divisions. Ford Model E is to focus on electric vehicles; Ford Blue is to focus on internal combustion vehicles; and the existing commercial division is to be rebranded as Ford Pro, to focus on vehicle distribution and service.

                        In August 2022, Ford announced it planned layoffs of roughly 3,000 employees and contract workers, confirming earlier reporting. The cuts would mostly affect divisions in the US, Canada, and India, which Jim Farley said would allow the company to prepare for the future of electric, software-heavy vehicles.

                        In February 2023, Ford announced that it was going to cut 3,800 jobs across Europe, with the job cuts mainly focusing on their German and British workforce. Ford will be cutting 2,300 jobs from Germany, 1,300 from the United Kingdom, and an additional 200 jobs in the rest of Europe, according to the head of Ford Germany, Martin Sander. The cuts will mainly be done to the company's engineers.

                        Ford announced that their electric vehicle business had lost $3 billion before taxes over the past two years and will lose a similar amount in 2023 as the company looks to significantly invest in Electric Technology. The Ford Model E is expected to be profitable by 2026.

                        In April 2023, United Kingdom ministers approved Ford's BlueCruise technology. Because of this assisted driving technology, Ford drivers can now legally take their hands off the wheel on certain roads. Its top speed is 129 km/h (80 mph). BlueCruise uses sensors and cameras to regulate the car's speed and to keep track of speed limits and road signs. It also monitors and keeps a safe distance from other vehicles. It also comes equipped with an eye-tracking system. If the driver stops looking at the road then the car will gradually reduce its speed. This technology will initially be offered in Ford's 2023 model of the electric Mustang Mach-E SUV. According to Thatcham Research, an automotive research company, this model is not a self-driving car. It is classified as a level 2 or partial automation assistance system. This means that technology controls two or more driving aspects but still requires human driver control in cases of emergencies. The driver is still legally responsible for accidents</p>

                    <h3>Events</h3>

                </Modal.Body>
            </Modal>
        </>
    );
}

export default Popup_Ford;